spring.application.name=air-asset-management
server.port=8080

# SQL Server connection
spring.datasource.url=jdbc:sqlserver://generator-manager.database.windows.net:1433;databaseName=manager;encrypt=true;trustServerCertificate=true
spring.datasource.username=generator-manager
spring.datasource.password=1234genman$
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
